#!/usr/bin/env python3
"""
Generate LEADERBOARD.md from community benchmark results.

Usage:
    python leaderboard.py
"""

import json
from pathlib import Path


COMMUNITY_DIR = Path(__file__).parent / "results" / "community"
OUTPUT_FILE = Path(__file__).parent / "LEADERBOARD.md"


def load_results():
    rows = []
    for f in sorted(COMMUNITY_DIR.glob("*.json")):
        try:
            data = json.loads(f.read_text())
        except (json.JSONDecodeError, OSError):
            continue

        sys = data.get("system", {})
        scoring = data.get("scoring", {})
        gpu = data.get("gpu", {})
        practical = data.get("practical", {})

        # Score
        score = scoring.get("score_tok_s", 0)

        # GPU GEMM at 4096
        gemm4k = "—"
        for g in gpu.get("gemm", []):
            if g.get("size") == 4096:
                gemm4k = f"{g['gflops']:,.0f}"

        # FP16 speedup
        fp16 = gpu.get("fp16_fp32", {})
        fp16x = f"{fp16['fp16_speedup']:.2f}" if "fp16_speedup" in fp16 else "—"

        # Max feasible model (LoRA)
        max_lora = "—"
        for m in reversed(practical.get("feasibility", [])):
            if m.get("fits_lora"):
                max_lora = m["model"]
                break

        rows.append({
            "chip": sys.get("chip", "?"),
            "ram": sys.get("ram_gb", "?"),
            "gpu_cores": sys.get("gpu_cores", "?"),
            "score": score,
            "gemm4k": gemm4k,
            "fp16x": fp16x,
            "max_lora": max_lora,
            "torch": sys.get("torch_version", "?"),
            "file": f.name,
        })

    rows.sort(key=lambda r: r["score"], reverse=True)
    return rows


def generate_markdown(rows):
    lines = [
        "# Leaderboard",
        "",
        "Community benchmark results sorted by transformer training throughput (d=1024).",
        "",
        "| Rank | Chip | RAM | GPU Cores | Score (tok/s) | GEMM 4K (GFLOPS) | FP16x | Max LoRA Model | PyTorch |",
        "|-----:|------|----:|----------:|--------------:|------------------:|------:|----------------|---------|",
    ]

    for i, r in enumerate(rows, 1):
        lines.append(
            f"| {i} "
            f"| {r['chip']} "
            f"| {r['ram']}GB "
            f"| {r['gpu_cores']} "
            f"| {r['score']:,} "
            f"| {r['gemm4k']} "
            f"| {r['fp16x']}x "
            f"| {r['max_lora']} "
            f"| {r['torch']} |"
        )

    lines.extend([
        "",
        "---",
        "",
        "**Submit your results:** Run `python bench.py --submit`, then open a PR adding your file from `results/community/`.",
        "",
        "*Generated by `python leaderboard.py`*",
        "",
    ])
    return "\n".join(lines)


def main():
    if not COMMUNITY_DIR.exists():
        print(f"No community results found at {COMMUNITY_DIR}")
        return

    rows = load_results()
    if not rows:
        print("No valid result files found.")
        return

    md = generate_markdown(rows)
    OUTPUT_FILE.write_text(md)
    print(md)
    print(f"\nWritten to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
